INSERT INTO GROUPS (NAME) VALUES ('Phoenix');
INSERT INTO GROUPS (NAME) VALUES ('Avalanche');
INSERT INTO GROUPS (NAME) VALUES ('Eclipse');
INSERT INTO GROUPS (NAME) VALUES ('Thunder');
INSERT INTO GROUPS (NAME) VALUES ('Vortex');
INSERT INTO GROUPS (NAME) VALUES ('Radiance');