CREATE TABLE STUDENTS
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    GROUP_ID NUMBER NOT NULL
);

CREATE TABLE groups
(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    C_VAL NUMBER DEFAULT 0 NOT NULL
);
