CREATE TABLE STUDENTS_LOG (
  LOG_ID NUMBER,
  LOG_DATE DATE,
  LOG_USERNAME VARCHAR2(50),
  LOG_OPERATION VARCHAR2(50),
  STUDENT_ID NUMBER,
  STUDENT_NAME VARCHAR2(50),
  STUDENT_GROUP_ID NUMBER
);

CREATE SEQUENCE STUDENTS_LOG_SEQ
START WITH 1
INCREMENT BY 1;


CREATE OR REPLACE TRIGGER STUDENTS_LOG_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
DECLARE
  OPERATION_TYPE VARCHAR2(50);
BEGIN
  IF INSERTING THEN
    OPERATION_TYPE := 'INSERT';
  ELSIF UPDATING THEN
    OPERATION_TYPE := 'UPDATE';
  ELSIF DELETING THEN
    OPERATION_TYPE := 'DELETE';
  END IF;
  
  INSERT INTO STUDENTS_LOG (LOG_ID, LOG_DATE, LOG_USERNAME, LOG_OPERATION, STUDENT_ID, STUDENT_NAME, STUDENT_GROUP_ID)
  VALUES (STUDENTS_LOG_SEQ.NEXTVAL, SYSDATE, USER, OPERATION_TYPE, :OLD.ID, :OLD.NAME, :OLD.GROUP_ID);
END;